spring:
  application:
    name: power-plant
  datasource:
    url: jdbc:h2:mem:powerplantdb
    username: powerplant
    password: powerplant
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:/db/migration
server:
  port: 8080  